# Special units
unit.overlord.count=1
unit.oracle.count=2
unit.raider.count=5
unit.scout.count=5
unit.shapeshifter.count=1
unit.leviathan.count=1

# Clan numbered units: one of each power 1..13 per clan and one of each clan's king unit
unit.fire.1.count=1
unit.fire.2.count=1
unit.fire.3.count=1
unit.fire.4.count=1
unit.fire.5.count=1
unit.fire.6.count=1
unit.fire.7.count=1
unit.fire.8.count=1
unit.fire.9.count=1
unit.fire.10.count=1
unit.fire.11.count=1
unit.fire.12.count=1
unit.fire.13.count=1
unit.fire.king.count=1

unit.earth.1.count=1
unit.earth.2.count=1
unit.earth.3.count=1
unit.earth.4.count=1
unit.earth.5.count=1
unit.earth.6.count=1
unit.earth.7.count=1
unit.earth.8.count=1
unit.earth.9.count=1
unit.earth.10.count=1
unit.earth.11.count=1
unit.earth.12.count=1
unit.earth.13.count=1
unit.earth.king.count=1

unit.water.1.count=1
unit.water.2.count=1
unit.water.3.count=1
unit.water.4.count=1
unit.water.5.count=1
unit.water.6.count=1
unit.water.7.count=1
unit.water.8.count=1
unit.water.9.count=1
unit.water.10.count=1
unit.water.11.count=1
unit.water.12.count=1
unit.water.13.count=1
unit.water.king.count=1

unit.shadow.1.count=1
unit.shadow.2.count=1
unit.shadow.3.count=1
unit.shadow.4.count=1
unit.shadow.5.count=1
unit.shadow.6.count=1
unit.shadow.7.count=1
unit.shadow.8.count=1
unit.shadow.9.count=1
unit.shadow.10.count=1
unit.shadow.11.count=1
unit.shadow.12.count=1
unit.shadow.13.count=1
unit.shadow.king.count=1
