# Base scoring
score.correct.prophecy.multiplier=20
score.incorrect.prophecy.penalty.multiplier=-10
score.zero.prophecy.correct.multiplier=10
score.zero.prophecy.incorrect.multiplier=-10

# Bonus scoring 
bonus.requires.correct.prophecy=true
bonus.capture.king.fire=10
bonus.capture.king.earth=10
bonus.capture.king.water=10
bonus.capture.king.shadow=20
bonus.overlord.defeats.raider=30
bonus.oracle.defeats.overlord=50
